# Generated by Django 4.1.7 on 2023-04-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['created_at']},
        ),
    ]
